((nil . ((indent-tabs-mode         . nil)
         (require-final-newline    . t)
         (show-trailing-whitespace . t)
         (ah-project-headline . "geoid -- work efficiently with geographic data")
         (ah-project-license . lgpl)
         (ah-spdx-license . "LGPL-3.0-or-later")
         (bug-reference-url-format . "https://github.com/alex-hhh/geoid/issues/%s")
         (bug-reference-bug-regexp . "\\#\\(?2:[0-9]+\\)\\>")
         ))
 (yaml-mode . ((mode . goto-address)
               (mode . bug-reference)))
 (shell-script-mode . ((mode . goto-address)
                       (mode . bug-reference)))
 (log-view-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (log-edit-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (markdown-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (racket-mode . ((mode . goto-address)
                 (mode . bug-reference)))
 (sql-mode . ((mode . goto-address)
              (mode . bug-reference)
              (sql-product . sqlite))))
